### ISSUE TITLE
Setup not working on MacOS

### ISSUE THREAD

**Issue by a-w11** [nielsenramon/chalk#198] opened 2019-12-18 22:54 UTC
How to resolve?

`sysninja:chalk sysninja$ npm run local

> chalk@ local /Users/sysninja/Dropbox/blog-wnuk/chalk
> bundle exec jekyll serve --drafts

Configuration file: /Users/sysninja/Dropbox/blog-wnuk/chalk/_config.yml
            Source: /Users/sysninja/Dropbox/blog-wnuk/chalk
       Destination: /Users/sysninja/Dropbox/blog-wnuk/chalk/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.8.6 | Error:  wrong number of arguments (given 2, expected 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chalk@ local: `bundle exec jekyll serve --drafts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chalk@ local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sysninja/.npm/_logs/2019-12-18T22_52_29_452Z-debug.log`

**Comment by gsaslis** [comment] 2019-12-21 19:42
this looks like a duplicate of #195 

@a-w11 please try the solution proposed there, it worked for me ;)

**Closed** 2019-12-27 22:32 UTC
